apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgCKhgMdLTTc+wpsU0oPBtqtrlFUgILZP/z8SIduVcV7DF38evw8qVEphcE/rdXR+xX5OwJkcpHJBIrucW2+cFNRUj746S3zlzbK61GKk+fXUbRJhchHShBrLid07OcsptIij7k/A+m3sIp2+91VfMF1pdZrxxgiJKSY6WcPTxW3Gjg5tRps+ptWYEZE8+3TNgp62LS9NWAr1T2ghBEgkyFioSUr9J0bjFPh24td/i4I7QqCE9GIpjfZkOp927CovEp+YCd4olgJESlUJHYF4ZCrmi0RoDT+MCi475fNBheFKvyXqmg2refnox/ztTvUP/ln5ezMF/C53IYFZ1QgN1cUUw8JYS9Av9K6LwDIqcg4FsTnHMLJkAiME2pnti34On7pa8FDH3VZGJz7V4krYSCtl2y47Yxe28/HZNEaZEejUCZ/GPZA7l70z7YAytJiUONmWDuLR4pmH/ttifcDdvgyujxerREUFlPnn1zxgVWtmc2l9pJraeopteCmOre9mdGLOBRvWLBwrax6CfFzTt+7SSvwVw1HwvX5pEjWZYs+CAAqimjbz9bllFRws/5EjRdI+hiPxs63fG2tXCSZpfJbdjvAsuthKQLyTH0+wCiuquCq5uupeuI7wmMpuGE7eZfz3I02k18rp6xueGXZOvvIBLZJg5kM+3h9YO+YLUSjoXAEXtwOzKyS/caZFohS1G8JKhP6bZJxkQg=
    username: AgCH91GgXNTHmJYwuamEW6llvWXcUm1prB/sNGJteurv2V8IN1rD+ihnhyVTWZ6I8j7ft15YmZ1ANtiaHbB3hBpZ2i8RHgkplplV4xzw+U/uR7Jzyb8NOF4k/KcIVGF7FkmQLC/IfF+P3tHj43pAmaSYAZoc3y0oLKxDu/y6Qi1VuA0OAq1SjpHxWxh8HjvyvwVl0eQUpqw8LMmT5/2Mzsw8lcDvjCeFgnj8itVTL3ZUEMDxZUVty9lPh5zHBPzpj1HXJ0vCfgWmiSkGbZTz4MlNiLXGyLGI98FmBU7cZiEo0OdTU3mDwt9LpACo/bXL/DQmypscLB2AGr+/VtV29BydOv9XPMvfrk2fdi17xKJK7PhJBQTqPNGgqy1uetsViQqcSnmNQ3JLSwt3BNawHqb99ib5OA+evMW8zOw/Q9NRPHSUPnlDw83upRl/DGx5P7iazsvoUDN0Z07638LLhfGgrojVqQoEUUDrypwsQeRirmtcMPgtXauYRpje+V05SMy0/8EVFc51WRF8zAplxwR5qm2rUU06MQc11dYgVq5n+dQfWYiXy568Bep8wEOAT4jDBjH4Ve13UXUdfS4Ah1dLNsR6JBjJfpwmcmNa+1NMw5WoFnkHW6p/aXupOMCGwh0nNLxD0SjyXSZVImppmCPsUMu4q64LrrNYvQsHsbwYroSO21lm+aE81hXk1+TE0WLkGKl+qkFq
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

